// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feamafjxyjhhniestcyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlYW1hZmp4eWpoaG5pZXN0Y3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjc1MzYsImV4cCI6MjA3Mjc0MzUzNn0.6BWTGHDMZV91vlfjxZO_X--lIkH0UoJs608lptf6Z3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});